version: "3.7"

services:

  opcua-monitor:
    depends_on:
      - influxdb
      - nats
      - redis
    build:
      context: .
      dockerfile: ./opcua-monitor/Dockerfile
    image: opcua-monitor
    volumes:
      - type: volume
        source: opcua-logs
        target: /var/log/opcua
    container_name: opcua_monitor
    command:
      - --endpoint=opc.tcp://192.168.0.103:53530/OPCUA/SimulationServer
      - --params=parameters.txt
      - --dbaddress=http://influxdb:8086
      - --database=system_indicators
      - --cacheaddress=redis:6380
      - --brokerhost=nats://nats:4222
      - --topic=measures
      - --capacity=5
      - --launch-timeout=3
  
  alerter:
    depends_on:
      - influxdb
      - redis
      - nats
      - opcua-monitor
    build:
      context: .
      dockerfile: ./alerter/Dockerfile
    image: alerter
    volumes:
      - type: volume
        source: alerter-logs
        target: /var/log/alerter
    container_name: alert_server
    command:
      - --cacheaddress=redis:6380
      - --dbaddress=http://influxdb:8086
      - --database=system_indicators
      - --brokerhost=nats://nats:4222
      - --topic=measures
      - --capacity=5
      - --launch-timeout=4

  web-server:
    depends_on:
      - opcua-monitor
      - nats
      - redis
    build:
      context: .
      dockerfile: ./web-server/Dockerfile
    image: web-server
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: web-logs
        target: /var/log/web
    container_name: web_server
    command:
      - --cacheaddress=redis:6380
      - --brokerhost=nats://nats:4222
      - --topic=measures
      - --launch-timeout=4

  nats:
    image: nats
    ports:
      - 4222:4222
    volumes:
      - type: volume
        source: nats-logs
        target: /var/log/nats
    container_name: nats_server
    command:
      - --log=/var/log/nats/log.txt

  redis:
    image: redis
    ports:
      - 6380:6380
    volumes:
      - type: volume
        source: redis-logs
        target: /var/log/redis
      - type: volume
        source: redis-data
        target: /data
    container_name: redis_server
    command:
      - --port 6380
      - --appendonly yes

  influxdb:
    image: influxdb:1.7.8-alpine
    ports:
      - 8086:8086
    volumes:
      - type: volume
        source: influxdb-data
        target: /var/lib/influxdb
    container_name: influx_server

volumes:
  nats-logs:
  redis-logs:
  redis-data:
  web-logs:
  opcua-logs:
  alerter-logs:
  influxdb-data: