version: "3.7"

services:

  opcua-monitor:
    depends_on:
      - influxdb
    build:
      context: .
      dockerfile: ./opcua-monitor/Dockerfile
    image: opcua-monitor
    volumes:
      - type: volume
        source: opcua-logs
        target: /var/log/opcua
    container_name: opcua_monitor
    command:
      - --endpoint=opc.tcp://192.168.0.103:53530/OPCUA/SimulationServer
      - --dbaddress=http://influxdb:8086
      - --database=system_indicators
      - --capacity=60

  web-server:
    depends_on:
      - opcua-monitor
      - influxdb
    build:
      context: .
      dockerfile: ./web-server/Dockerfile
    image: web-server
    container_name: web_server

  nats:
    image: nats
    ports:
      - 4222:4222
    volumes:
      - type: volume
        source: nats-logs
        target: /var/log/nats
    container_name: nats_server
    command:
      - --log=/var/log/nats/log.txt

  influxdb:
    image: influxdb:1.7.8-alpine
    ports:
      - 8086:8086
    volumes:
      - type: volume
        source: influxdb-data
        target: /var/lib/influxdb
    container_name: influx_server
  
  chronograf:
    depends_on:
      - influxdb
    image: chronograf:1.7.14-alpine
    ports:
      - 8888:8888
    volumes:
      - type: volume
        source: chronograf-data
        target: /var/lib/chronograf
    container_name: chronograf_server
    command:
      - --influxdb-url=http://influxdb:8086

volumes:
  nats-logs:
  web-logs:
  opcua-logs:
  influxdb-data:
  chronograf-data: